/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Converts Arrow IPC bytes to a JSON string.
 *
 * Accepts both Arrow IPC file format and streaming format.
 * Returns a JSON array string where each element is a row object
 * with column names as keys.
 *
 * - Null values are omitted from output objects.
 * - `Map<Utf8, *>` columns are emitted as JSON objects.
 * - `Int64`/`UInt64` values exceeding 2^53 are emitted as strings.
 * - Temporal types are cast to their string representation.
 */
export declare function arrowIpcToJson(data: Buffer): string
