/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Converts Arrow IPC bytes to a JSON string.
 *
 * Accepts both Arrow IPC file format and streaming format.
 * Returns a JSON array string where each element is a row object
 * with column names as keys.
 *
 * - Null values are omitted from output objects.
 * - `Map<Utf8, *>` columns are emitted as JSON objects.
 * - `Int64`/`UInt64` values exceeding 2^53 are emitted as strings.
 * - Temporal types are cast to their string representation.
 */
export declare function arrowIpcToJson(data: Buffer): string

/**
 * Converts Arrow IPC bytes to a columnar JSON string.
 *
 * Output format: `{"col1":[v1,v2,...],"col2":[v1,v2,...],...}`
 *
 * Each key is a column name, each value is a flat array of all row values
 * for that column. This format is ~30-40% smaller than the row-object
 * format because column names appear only once, leading to proportionally
 * faster `JSON.parse` on the JS side.
 *
 * Null values and empty maps are written as `null`.
 */
export declare function arrowIpcToJsonColumns(data: Buffer): string
