/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Converts Arrow IPC bytes to JavaScript objects.
 *
 * Accepts both Arrow IPC file format and streaming format.
 * Returns an array of row objects with column names as keys,
 * constructed directly through N-API without JSON serialization.
 *
 * - Null values are omitted from output objects.
 * - `Map<Utf8, *>` columns are emitted as plain objects (`{key: value}`).
 * - `Int64`/`UInt64` values exceeding 2^53 are emitted as strings.
 * - Temporal types are cast to their string representation.
 */
export declare function arrowIpcToJson(data: Buffer): any
